budget/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
	url(r'^newbudget/', 'budget.views.new_budget_view'),
	url(r'^newpurchase/', 'budget.views.new_purchase_view'),
	url(r'^delete/(?P<purchase_id>\d+)/$', 'budget.views.delete_purchase_view'),
	url(r'^edit/(?P<purchase_id>\d+)/$', 'budget.views.edit_purchase_view'),
)

my2cents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'my2cents.views.home', name='home'),
    url(r'^', include('reg_login.urls')),
    url(r'^budgets/', include ('budget.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/profile', 'my2cents.views.profile_view'),
)

urlpatterns += staticfiles_urlpatterns();

budget/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal

# Create your models here.
class BudgetModel(models.Model):
	id = models.AutoField(primary_key=True)
	user_account = models.ForeignKey(User)
	budget_amount = models.DecimalField(max_digits=15, decimal_places=2)
	is_weekly = models.BooleanField()
	budget_month = models.IntegerField()
	budget_year = models.IntegerField()
	end_date = models.DateField()

class PurchaseModel(models.Model):
	CATEGORIES = (
		(1, 'Food'),
		(2, 'Gas'),
		(3, 'Entertainment'),
		(4, 'Bills'),
		(5, 'Misc'),
	)
	id = models.AutoField(primary_key=True)
	budget = models.ForeignKey(BudgetModel)
	name = models.CharField(max_length=100)
	price = models.DecimalField(max_digits=15, decimal_places=2)
	category = models.IntegerField(choices=CATEGORIES)
	date_of_purchase = models.DateField(auto_now=True)

	def price_to_string(self):
		return self.price.quantize(Decimal('.00'))

	def category_to_string(self):
		return self.CATEGORIES[self.category][1]

budget/forms.py
from django.forms import ModelForm, TextInput, NumberInput
from budget.models import BudgetModel, PurchaseModel

class BudgetForm(ModelForm):
	class Meta:
		model = BudgetModel
		fields = ['budget_amount', 'is_weekly']
		widgets = {
			'budget_amount' : NumberInput(attrs={'placeholder':'Enter Budget Amount'}),
		}
		labels = {
			'is_weekly' : 'One Week?',
		}

class PurchaseForm(ModelForm):
	class Meta:
		model = PurchaseModel
		fields = ['name', 'price', 'category']
		widgets = {
			'name' : TextInput(attrs={'placeholder':'Enter Purchase Name:'}),
			'price' : NumberInput(attrs={'placeholder':'Enter Price:'}),
		}

budget/views.py
from django.template import Context
from django.shortcuts import render
from django.contrib import auth
from django.core.context_processors import csrf
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from budget.forms import BudgetForm, PurchaseForm
from budget.models import BudgetModel, PurchaseModel
from datetime import datetime, date, timedelta
import calendar
# These views will all require login, using the login_required
# decorator

@login_required
def new_budget_view(request):
	if request.method == 'POST':
		form = BudgetForm(request.POST)
		if form.is_valid():
			amount = form.cleaned_data['budget_amount']
			weekly = form.cleaned_data['is_weekly']
			month = datetime.today().month
			year = datetime.today().year
			end_date = datetime.today()
			if weekly:
				today = datetime.today().weekday()
				difference = 6-today
				delta = timedelta(days=difference)
				end_date = end_date+delta
			else:
				end_day = calendar.monthrange(year, month)[1]
				end_date = date(year, month, end_day)

			model = BudgetModel(user_account=request.user,
				budget_amount=amount, is_weekly=weekly,
				budget_month=month, budget_year=year,
				end_date=end_date)
			model.save()
			return HttpResponseRedirect('/accounts/profile')

	context = RequestContext(request)
	context['form'] = BudgetForm()
	context.update(csrf(request))
	return render(request, 'budget/newbudget.html', context)

@login_required
def new_purchase_view(request):
	if request.method == 'POST':
		form = PurchaseForm(request.POST)
		if form.is_valid():
			purchase_name = form.cleaned_data['name']
			purchase_price = form.cleaned_data['price']
			purchase_category = form.cleaned_data['category']
			purchase_date = datetime.today()
			purchase_budget = BudgetModel.objects.get(end_date__gte=datetime.today(),
			user_account=request.user)
			purchase_budget.budget_amount -= purchase_price
			purchase_budget.save()
			model = PurchaseModel(budget=purchase_budget,
				name=purchase_name, price=purchase_price,
				category=purchase_category-1, 
				date_of_purchase=purchase_date)
			model.save()
			return HttpResponseRedirect('/accounts/profile')

	context = RequestContext(request)
	context['form'] = PurchaseForm()
	context.update(csrf(request))
	return render(request, 'budget/newpurchase.html', context)

@login_required
def delete_purchase_view(request, purchase_id=0):
	purchase = PurchaseModel.objects.get(id__exact=purchase_id)
	budget = BudgetModel.objects.get(end_date__gte=datetime.today(),
		user_account=request.user)
	budget.budget_amount += purchase.price
	budget.save()
	purchase.delete()

	return HttpResponseRedirect('/accounts/profile')

@login_required
def edit_purchase_view(request, purchase_id=0):
	purchase = PurchaseModel.objects.get(id__exact=purchase_id)
	budget = BudgetModel.objects.get(end_date__gte=datetime.today(),
		user_account=request.user)
	if request.method == 'POST':
		form = PurchaseForm(request.POST)
		if form.is_valid():
			# Remove former price from budget, change data,
			# add new price to budget
			budget.budget_amount += purchase.price
			purchase.name = form.cleaned_data['name']
			purchase.price = form.cleaned_data['price']
			purchase.category = form.cleaned_data['category']-1
			budget.budget_amount -= purchase.price
			purchase.save()
			budget.save()
		return HttpResponseRedirect('/accounts/profile')
	else:
		form = PurchaseForm()
		context = RequestContext(request)
		context['form'] = PurchaseForm()
		context['purchase'] = purchase
		context.update(csrf(request))
		return render(request, 'budget/editpurchase.html', context	
)		

templates/budget/editpurchase.html
{% extends "base.html" %}
{% load static %}

{% block title %} My2Cents-Edit Purchase {% endblock %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "assets/css/newpurchase.css" %}">
{% endblock %}
{% block link%}
<a href="/accounts/profile/">
{% endblock %}
{% block endlink%}
</a>
{% endblock %}
{% block content %}
	<h1>Edit {{ purchase.name }}</h1>
	<form action="/budgets/edit/{{ purchase.id }}/" method="post" id="purchase_form"> 
		{% csrf_token %}
		{{ form.name }} <br>
		{{ form.price }} <br>
		<big><big>
		<label for="id_category">Select a Category:</label>
		</big></big>
		{{ form.category }} <br>
		<input type="submit" value="Edit Purchase" id="button-link">
	</form>
{% endblock %}

templates/budget/newbudget.html
{% extends "base.html" %}
{% load static %}

{% block title %}My2Cents-Add Budget{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "assets/css/newbudget.css" %}">
{% endblock %}

{% block link%}
<a href="/accounts/profile/">
{% endblock %}
{% block endlink%}
</a>
{% endblock %}

{% block content %}

	<h1>Add a new budget:</h1>
	<form action="/budgets/newbudget/" method="post" id="budget_form"> {% csrf_token %}
		{{ form.budget_amount }} <br>
		<big><big>
		<label for="id_is_weekly">One Week?</label>
		</big></big>
		{{ form.is_weekly}} <br>

		<input type="submit" value="Create Budget" id="link-button">
	</form>
{% endblock %}

templates/budget/newpurchase.html
{% extends "base.html" %}
{% load static %}
{% block title %}My2Cents- Add Budget{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static "assets/css/newpurchase.css" %}">
{% endblock %}

{% block link%}
<a href="/accounts/profile/">
{% endblock %}
{% block endlink%}
</a>
{% endblock %}

{% block content %}		
	<h1>Add a new purchase</h1>
	<form action="/budgets/newpurchase/" method="post" id="purchase_form"> 
		{% csrf_token %}
		{{ form.name }} <br>
		{{ form.price }} <br>
		<big><big>
		<label for="id_category">Select a Category:</label>
		</big></big>
		{{ form.category }} <br>
		<input type="submit" value="Enter Purchase" id="link-button">
	</form>
{% endblock %}